# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20170625_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_checked',
            field=models.BooleanField(default=False),
        ),
    ]
