# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_user_is_email_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_jwxt_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
