# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_auto_20170625_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='QQnumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
