# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_auto_20170628_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default='', max_length=20)),
                ('latitude', models.CharField(default='', max_length=20)),
                ('locationName', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
