# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOneDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddOneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='./media/image/goods/addone')),
                ('goodsname', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=20)),
                ('is_adjustable', models.BooleanField(default=False)),
                ('pub_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=2000)),
                ('star', models.IntegerField(default=0)),
                ('comments_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BuyDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='./media/image/goods/buy')),
                ('goodsname', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=20)),
                ('is_adjustable', models.BooleanField(default=False)),
                ('is_dealed', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('pub_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='QaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('pub_change_date', models.DateTimeField(auto_now=True)),
                ('answer', models.ManyToManyField(to='Market.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='SellDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='./media/image/goods/sell')),
                ('goodsname', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=20)),
                ('is_adjustable', models.BooleanField(default=False)),
                ('is_dealed', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('pub_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='headImage',
            field=models.ImageField(blank=True, null=True, upload_to='./media/image/users/headimage'),
        ),
        migrations.AddField(
            model_name='sellinfo',
            name='pub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selldeal',
            name='info',
            field=models.ManyToManyField(to='Market.SellInfo'),
        ),
        migrations.AddField(
            model_name='selldeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qainfo',
            name='que_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyinfo',
            name='pub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buydeal',
            name='info',
            field=models.ManyToManyField(to='Market.BuyInfo'),
        ),
        migrations.AddField(
            model_name='buydeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='comments',
            field=models.ManyToManyField(to='Market.Comment'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addoneinfo',
            name='in_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addonedeal',
            name='info',
            field=models.ManyToManyField(to='Market.AddOneInfo'),
        ),
        migrations.AddField(
            model_name='addonedeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
