# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0008_auto_20170701_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellinfo',
            name='is_adjustable',
        ),
        migrations.AlterField(
            model_name='addoneinfo',
            name='picture',
            field=models.ImageField(blank=True, default='media/image/goods/defaultgoodsimage.jpg', null=True, upload_to='./media/image/goods/addone'),
        ),
        migrations.AlterField(
            model_name='buyinfo',
            name='picture',
            field=models.ImageField(blank=True, default='media/image/goods/defaultgoodsimage.jpg', null=True, upload_to='./media/image/goods/buy'),
        ),
        migrations.AlterField(
            model_name='sellinfo',
            name='picture',
            field=models.ImageField(blank=True, default='media/image/goods/defaultgoodsimage.jpg', null=True, upload_to='./media/image/goods/sell'),
        ),
        migrations.AlterField(
            model_name='user',
            name='headImage',
            field=models.ImageField(blank=True, default='media/image/users/defaultheadimage.jpg', null=True, upload_to='./media/image/users/headimage'),
        ),
    ]
