# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0010_sellinfo_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonedeal',
            name='info',
        ),
        migrations.RemoveField(
            model_name='addonedeal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='addoneinfo',
            name='in_users',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='buydeal',
            name='info',
        ),
        migrations.RemoveField(
            model_name='buydeal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='buyinfo',
            name='pub_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qainfo',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='qainfo',
            name='que_user',
        ),
        migrations.RemoveField(
            model_name='selldeal',
            name='info',
        ),
        migrations.RemoveField(
            model_name='selldeal',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='isInfoFilled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AddOneDeal',
        ),
        migrations.DeleteModel(
            name='AddOneInfo',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='BuyDeal',
        ),
        migrations.DeleteModel(
            name='BuyInfo',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='QaInfo',
        ),
        migrations.DeleteModel(
            name='SellDeal',
        ),
    ]
