# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0012_sustcnewsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustcnewsinfo',
            name='img_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
