# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0017_user_realname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicForumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apartment', models.CharField(default='', max_length=20)),
                ('Title', models.CharField(default='', max_length=20)),
                ('Lecturer', models.CharField(default='', max_length=20)),
                ('Time', models.CharField(default='', max_length=20)),
                ('Location', models.CharField(default='', max_length=20)),
                ('day', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
