# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0018_academicforuminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_info',
            name='detail_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='img_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
