# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0019_auto_20170803_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pushID',
            field=models.CharField(default='', max_length=50),
        ),
    ]
