# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0021_academicforuminfo_detail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionUsedTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getBusTime', models.IntegerField(default=0)),
                ('getTeacherInfo', models.IntegerField(default=0)),
                ('getForumInfo', models.IntegerField(default=0)),
                ('open_Confession_Wall', models.IntegerField(default=0)),
                ('open_Activity_Wall', models.IntegerField(default=0)),
                ('open_Blame_Wall', models.IntegerField(default=0)),
                ('open_MakeFriends_Wall', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserJoinForumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=20)),
                ('Apartment', models.CharField(default='', max_length=20)),
                ('Detail_url', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity_wall',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity_wall',
            name='startTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
