# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0022_auto_20170805_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo_updateEveryTenMin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default='', max_length=20)),
                ('latitude', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
