# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0023_userinfo_updateeverytenmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blame_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blameID', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=100)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blame_star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blameID', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blame_wall',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blame_wall',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
