# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0025_userinfo_updateeverytenmin_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_usr', models.CharField(default='', max_length=20)),
                ('lib_pwd', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
