# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0027_mainpagepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeWea', models.CharField(default='', max_length=200)),
                ('nighttimeWea', models.CharField(default='', max_length=200)),
                ('pub_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
