# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0028_todayweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionusedtimes',
            name='borrow_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='functionusedtimes',
            name='search_books',
            field=models.IntegerField(default=0),
        ),
    ]
