# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0030_auto_20170813_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_wall',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
