# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0031_activity_wall_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_wall',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
