# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0034_activity_wall_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_wall',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
