# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0037_blame_wall_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('content', models.CharField(default='', max_length=200)),
                ('host', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('content', models.CharField(default='', max_length=200)),
                ('host', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
