# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0038_clubactivity_officialactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=1000)),
                ('intro', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('pageurl', models.CharField(default='', max_length=1000)),
                ('pictureurl', models.CharField(default='', max_length=1000)),
                ('videourl', models.CharField(default='', max_length=1000)),
                ('changeDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
